
<div id="jssor_1">
	<!-- Images you pick go here -->
	<div class="slides" data-u="slides">
		<div>
			<img data-u="image" src="images/genessisbanner.jpg" alt="placeholder"/>
		</div>
		<div>
			<img data-u="image" src="images/leobanner.jpg" alt="placeholder"/>
		</div>
		<div>
			<img data-u="image" src="images/qianwenbanner.jpg" alt="placeholder"/>
		</div>
	</div>
	<!-- Bullet Navigator -->
	<div data-u="navigator" class="jssorb032" data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
		<div data-u="prototype" class="i">
			<svg class="svg01" viewbox="0 0 16000 16000">
			<circle class="b" cx="8000" cy="8000" r="5800"></circle>
			</svg>
		</div>
	</div>
	<!-- Arrow Navigator -->
	<div data-u="arrowleft" class="jssora051" data-autocenter="2" data-scale="0.75" data-scale-left="0.75">
		<svg class="svg02" viewbox="0 0 16000 16000">
		<polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>
		</svg>
	</div>
	<div data-u="arrowright" class="jssora051" data-autocenter="2" data-scale="0.75" data-scale-right="0.75">
		<svg class="svg03" viewbox="0 0 16000 16000">
		<polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>
		</svg>
	</div>
</div>