<!DOCTYPE html>
<html lang="en">
<head>
	<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300italic,regular,italic,700,700italic&subset=latin-ext,greek-ext,cyrillic-ext,greek,vietnamese,latin,cyrillic" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="css/sliderdefault.css">
	<link rel="stylesheet" href="css/styles.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

